### ISSUE TITLE
errors with the save game tool

### ISSUE THREAD

**Issue by tunip3** [tuxuser/py-durango-tools#2]
with the construct module installed (https://pypi.python.org/pypi/construct) :

usage: savegame_enum.py [-h] [--output OUTPUT] path
savegame_enum.py: error: the following arguments are required: path

withount it:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\OneDrive\Documents\xbox one reverse engineering\py-durango-tools-master\hdd\savegame_enum.py", line 11, in <module>
    from fileformat.savegame_container import ContainerIndex, ContainerBlob, CONTAINERS_INDEX
  File "C:\Users\user\OneDrive\Documents\xbox one reverse engineering\py-durango-tools-master\fileformat\savegame_container.py", line 3, in <module>
    from construct import this, Struct, Array
ModuleNotFoundError: No module named 'construct'

any example of how i would get this to work

**Comment by tunip3** [comment]
also which version of python 3 is recomended

**Comment by tuxuser** [comment]
Python 3.4 or greater
